- job: AzDevOpsLinux
  displayName: AzDevOps Linux
  pool:
    vmImage: ubuntu-16.04

variables:
  solution: '**/dirs.sln'
  BuildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'
  DotNetCoreVersion: '3.1.201'

steps:
 - task: UseDotNet@2
    displayName: 'Install .NET Core $(DotNetCoreVersion)'
    inputs:
      packageType: 'sdk'
      version: $(DotNetCoreVersion)

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      arguments: '-property:"Platform=$(BuildPlatform);Configuration=$(BuildConfiguration)"'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: 'test'
      arguments: '--no-build -restore:false -property:VSTestNoBuild=true'
