//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceProviders.ActiveMQ {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceProviders.ActiveMQ.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAA/1BMVEVHcEwxABcPAAcDAAEXAAsuABYMAAZOACYCAAAGAAMFAAEhABBOACZCACAyABhEACFEACErABQOAAZZACssABUhABBBAB9UAChXACtKACRKACQ8AB0NAAY2ABo+AB4/AB5oADO4uLhpBDS3t7dmADL///9eAC6XcYKtoKZkADGnk5ukjJZsCzlwFUB0Hke3tba1srSDQ2CqmqG0sLJ7MVOTaXuITmmwpaqBPFylkJmbeIfm2N6KVGx4KU6yqa2GSWV/N1jOs76PXXOdfovVvsizrbCufpKSZHmhh5LDo6+TUG7Yw8vp3uKYW3Xu5un8+vq0r7Gpdoy4i5+6kqLayM9WdZUQAAAAIHRSTlMAuCIFRoEb/gERClzt0KfG9ps0/49s7Pb81+GbK9aytz26P6AAAAQASURBVFjDpVeHduIwEKSX0AkQLg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IconUri {
            get {
                return ResourceManager.GetString("IconUri", resourceCulture);
            }
        }
    }
}
